name: CI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'todogroup/repolinter'
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run a multi-line script
        run: |
          npm --version
          gem --version
